title: SheLLiE
author: Janvi Rathi
email: janvirathee10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  will do it later

# social links
twitter_username: NA # DO NOT include the @ character, or else the build will fail!
github_username:  shellie_10 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
