title: Janvi Rathi
author: GitHub User
email: janvirathee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hellow People,
  so we creating something here, let me tell you guys about me
  I'm Janvi Rathi, an UG 2nd Year CSE from AIT Pune. 
  
  Exploring Github!!

# social links
twitter_username: shellie_10 # DO NOT include the @ character, or else the build will fail!
github_username:  shellie_10 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
